### ISSUE TITLE
Bug: App not working

### ISSUE THREAD

**Issue by hiimbex** [wip/app#122]
See: https://github.com/probot/probot/pull/650 I changed the title twice, and the wip status still didn't get reset.

**Comment by gr2m** [comment]
It’s blocked  because of this commit: https://github.com/probot/probot/pull/650/commits/007b95350868887965c708ac81819735ed06fdb5

The current WIP looks into title, commit messages and labels. You can’t override the status, the new version will be able to do that, see https://github.com/wip/app/pull/94
