### ISSUE TITLE
Loading labels for private repositories fails

### ISSUE THREAD

**Issue by raivil** [wip/app#76]
I started using WIP on a private github repository and it was working as expected.
Today however, it's not working anymore. It's affecting all my private repositories that had the app installed.

I'm using it by adding "wip" to pull request title. It goes to `"Pending — work in progress – do not merge!"` but whenever removing it does not passes the check.

Is anyone experiencing problems as well?

**Comment by gr2m** [comment]
Hmm, sorry for that! I was able to reproduce the issue and am looking into it now

**Comment by gr2m** [comment]
It looks like the problem is related to the check of labels at 
https://github.com/wip/app/blob/66cebb10f508bd62059e30113f89f1034b7217f9/lib/handle-pull-request-change.js#L30-L32

It works fine for public repositories but not for private ones. It is most likely a bug with the API, I’ll keep you posted. 

For the meantime I’ll disable the labels check for private repositories so the rest of the functionality keeps working

**Comment by gr2m** [comment]
@raivil the new version is deployed now, can you please give it another try?

**Comment by gr2m** [comment]
Turns out it’s somewhat related to the "Repository metadata" permission that I recently removed for the WIP app as it didn’t look like it was needed. But it seems that the lack of this permission causes problems for private repositories in some circumstances.

**Comment by raivil** [comment]
@gr2m It works!
