### ISSUE TITLE
Unable to remove WIP from repo?

### ISSUE THREAD

**Issue by robinwkurtz** [wip/app#82]
Hello! The past few days I've had some issues (Several isolated PRs on one repo) where either WIP is stuck on "Expected — Waiting for status to be reported" or falsely flagged as WIP.

I've attempted to add/remove "WIP" in the PRs name without luck. I've also ensured the target phrases are not in the PR conversations or in any commit title. Yet I am unable to remove the flag.

My final attempt was to remove WIP from the repo in question via the configuration page, however the flag is still present on that repo. Unfortunately the repo is private and so I cannot share it.

Any ideas on how I can debug the issue?

Thanks for your time & for the bot!

**Comment by gr2m** [comment]
Hey @robinwkurtz I’m sorry for the trouble! Could you check the branch protection settings? Maybe `wip` is still listed there as a required status even though it is no longer required? But either way, that looks like a bug to me, I’d ask support@github.com about it, they are very responsive and helpful :)

Regarding the problems you have seen, these should be resolved via #77. I recently removed the permission for repository meta data for the app, but turns out there is a bug in GitHub’s REST API, the WIP was no longer able to load labels for a pull request which prevented it from setting the status back to "success" when it was pending after you removed "wip" from the title. Could you please give it another try?

I also upgraded the hosting plan for the WIP app so it should be able to handle more request without problems. The last remaining problem that I’ll address soon is that WIP is hitting rate limits occasionally. 

I’d love if you gave WIP another try and if you run into trouble again please let me know, I’d be happy to investigate :)

**Comment by robinwkurtz** [comment]
Hello @gr2m, thanks of the quick response. I'm able to remove the integration via the protection settings like you've suggested so that's a good temporary fix for us.

We plan to keep using wip! However if it continues to be stuck on "Expected — Waiting for status to be reported" we might have to take a break. I assume this is due to not being able to handle all of the requests. A good problem to have I guess!

Thanks,

**Comment by gr2m** [comment]
> I assume this is due to not being able to handle all of the requests. A good problem to have I guess!

I’m working actively on that :) If you run into it again please let me know
